parameters:
  - name: serviceConnection
    type: string
  - name: environment
    type: string
  - name: catalogName
    type: string
  - name: metadataSchemaName
    type: string
  - name: runtimeSchemaName
    type: string
  - name: enableCdfForRuntime
    type: boolean
    default: true
  - name: enableCdfForMetadata
    type: boolean
    default: false
  - name: storageAccountName
    type: string
    default: ''
  - name: bronzeAccessConnectorId
    type: string
    default: ''
  - name: silverAccessConnectorId
    type: string
    default: ''
  - name: goldAccessConnectorId
    type: string
    default: ''

steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python 3.11'
    inputs:
      versionSpec: '3.11'
      addToPath: true

  - task: TerraformInstaller@0
    displayName: 'Install Terraform'
    inputs:
      terraformVersion: $(terraformVersion)

  - task: AzureCLI@2
    displayName: 'Setup Databricks Authentication'
    inputs:
      azureSubscription: ${{ parameters.serviceConnection }}
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        # Get Azure credentials
        export ARM_CLIENT_ID=$(az ad sp show --id $servicePrincipalId --query appId -o tsv)
        export ARM_TENANT_ID=$(az account show --query tenantId -o tsv)
        export ARM_SUBSCRIPTION_ID=$(az account show --query id -o tsv)
        
        # Set Databricks environment variables
        echo "##vso[task.setvariable variable=DATABRICKS_HOST]$(DATABRICKS_WORKSPACE_URL)"
        echo "##vso[task.setvariable variable=ARM_CLIENT_ID]$ARM_CLIENT_ID"
        echo "##vso[task.setvariable variable=ARM_TENANT_ID]$ARM_TENANT_ID"
        echo "##vso[task.setvariable variable=ARM_USE_MSI]true"
        
        # Log configuration (without sensitive data)
        echo "Environment: ${{ parameters.environment }}"
        echo "Catalog: ${{ parameters.catalogName }}"
        echo "Metadata Schema: ${{ parameters.metadataSchemaName }}"
        echo "Runtime Schema: ${{ parameters.runtimeSchemaName }}"

  - script: |
      # Initialize Terraform
      terraform init \
        -backend-config="resource_group_name=$(TF_STATE_RESOURCE_GROUP)" \
        -backend-config="storage_account_name=$(TF_STATE_STORAGE_ACCOUNT)" \
        -backend-config="container_name=$(TF_STATE_CONTAINER)" \
        -backend-config="key=orca-ddl/${{ parameters.environment }}/terraform.tfstate"
    displayName: 'Terraform Init'
    workingDirectory: $(System.DefaultWorkingDirectory)

  - script: |
      # Validate Terraform configuration
      terraform validate
    displayName: 'Terraform Validate'
    workingDirectory: $(System.DefaultWorkingDirectory)

  - script: |
      # Plan Terraform changes
      terraform plan \
        -var="catalog_name=${{ parameters.catalogName }}" \
        -var="metadata_schema_name=${{ parameters.metadataSchemaName }}" \
        -var="runtime_schema_name=${{ parameters.runtimeSchemaName }}" \
        -var="environment=${{ parameters.environment }}" \
        -var="enable_cdf_for_runtime=${{ parameters.enableCdfForRuntime }}" \
        -var="enable_cdf_for_metadata=${{ parameters.enableCdfForMetadata }}" \
        -var="storage_account_name=$(STORAGE_ACCOUNT_NAME)" \
        -var="bronze_access_connector_id=$(BRONZE_ACCESS_CONNECTOR_ID)" \
        -var="silver_access_connector_id=$(SILVER_ACCESS_CONNECTOR_ID)" \
        -var="gold_access_connector_id=$(GOLD_ACCESS_CONNECTOR_ID)" \
        -out=tfplan
    displayName: 'Terraform Plan'
    workingDirectory: $(System.DefaultWorkingDirectory)

  - script: |
      # Apply Terraform changes
      terraform apply -auto-approve tfplan
    displayName: 'Terraform Apply'
    workingDirectory: $(System.DefaultWorkingDirectory)
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

  - script: |
      # Show Terraform outputs
      terraform output -json > terraform-outputs.json
      cat terraform-outputs.json
    displayName: 'Capture Terraform Outputs'
    workingDirectory: $(System.DefaultWorkingDirectory)
    condition: succeeded()

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Terraform Plan'
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)/tfplan'
      ArtifactName: 'terraform-plan-${{ parameters.environment }}'
      publishLocation: 'Container'
    condition: always()

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Terraform Outputs'
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)/terraform-outputs.json'
      ArtifactName: 'terraform-outputs-${{ parameters.environment }}'
      publishLocation: 'Container'
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))