parameters:
  - name: serviceConnection
    type: string
  - name: environment
    type: string
  - name: adGroupEnvironment
    type: string
  - name: orcaCatalog
    type: string
  - name: orcaMetadataSchema
    type: string
  - name: orcaRuntimeSchema
    type: string
  - name: enableCdfForRuntime
    type: boolean
    default: true
  - name: enableCdfForMetadata
    type: boolean
    default: false
  - name: storageAccountName
    type: string
    default: ''
  - name: storageConnectorId
    type: string
    default: ''
  - name: databricksHost
    type: string
    default: ''
  


steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python 3.11'
    inputs:
      versionSpec: '3.11'
      addToPath: true

  - task: TerraformInstaller@0
    displayName: 'Install Terraform'
    inputs:
      terraformVersion: $(terraformVersion)

  - task: AzureCLI@2
    displayName: 'Setup Databricks Authentication'
    inputs:
      azureSubscription: ${{ parameters.serviceConnection }}
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        # Get Azure credentials
        export ARM_CLIENT_ID=$(az ad sp show --id $servicePrincipalId --query appId -o tsv)
        export ARM_TENANT_ID=$(az account show --query tenantId -o tsv)
        export ARM_SUBSCRIPTION_ID=$(az account show --query id -o tsv)
        
        # Set Databricks environment variables
        echo "##vso[task.setvariable variable=DATABRICKS_HOST]${{ parameters.databricksHost }}"
        echo "##vso[task.setvariable variable=ARM_CLIENT_ID]$ARM_CLIENT_ID"
        echo "##vso[task.setvariable variable=ARM_TENANT_ID]$ARM_TENANT_ID"
        echo "##vso[task.setvariable variable=ARM_USE_MSI]true"
        
        # Log configuration (without sensitive data)
        echo "Environment: ${{ parameters.environment }}"
        echo "Catalog: ${{ parameters.orcaCatalog }}"
        echo "Metadata Schema: ${{ parameters.orcaMetadataSchema }}"
        echo "Runtime Schema: ${{ parameters.orcaRuntimeSchema }}"

  - script: |
      # Initialize Terraform
      terraform init \
        -backend-config="resource_group_name=$(terraform_resource_group)" \
        -backend-config="storage_account_name=$(terraform_storage_account)" \
        -backend-config="container_name=$(terraform_container)" \
        -backend-config="key=orca-ddl/${{ parameters.environment }}/terraform.tfstate"
    displayName: 'Terraform Init'
    workingDirectory: $(System.DefaultWorkingDirectory)

  - script: |
      # Validate Terraform configuration
      terraform validate
    displayName: 'Terraform Validate'
    workingDirectory: $(System.DefaultWorkingDirectory)

  - script: |
      # Plan Terraform changes
      terraform plan \
        -var="orca_catalog=${{ parameters.orcaCatalog }}" \
        -var="orca_metadata_schema=${{ parameters.orcaMetadataSchema }}" \
        -var="orca_runtime_schema=${{ parameters.orcaRuntimeSchema }}" \
        -var="environment=${{ parameters.environment }}" \
        -var="enable_cdf_for_runtime=${{ parameters.enableCdfForRuntime }}" \
        -var="enable_cdf_for_metadata=${{ parameters.enableCdfForMetadata }}" \
        -var="storage_account_name=$(parameters.storageAccountName)" \
        -var="storage_connector_id=${{ parameters.storageConnectorId }}" \
        -var="ad_group_environment=${{ parameters.adGroupEnvironment }}" \
        -out=tfplan
    displayName: 'Terraform Plan'
    workingDirectory: $(System.DefaultWorkingDirectory)

  - script: |
      # Apply Terraform changes
      terraform apply -auto-approve tfplan
    displayName: 'Terraform Apply'
    workingDirectory: $(System.DefaultWorkingDirectory)
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

  - script: |
      # Show Terraform outputs
      terraform output -json > terraform-outputs.json
      cat terraform-outputs.json
    displayName: 'Capture Terraform Outputs'
    workingDirectory: $(System.DefaultWorkingDirectory)
    condition: succeeded()

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Terraform Plan'
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)/tfplan'
      ArtifactName: 'terraform-plan-${{ parameters.environment }}'
      publishLocation: 'Container'
    condition: always()

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Terraform Outputs'
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)/terraform-outputs.json'
      ArtifactName: 'terraform-outputs-${{ parameters.environment }}'
      publishLocation: 'Container'
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))