parameters:
  - name: serviceConnection
    type: string
  - name: databricksHost
    type: string
  - name: databricksAccountId
    type: string
    default: ''
  - name: environment
    type: string
  - name: adGroupEnvironment
    type: string
  - name: orcaCatalog
    type: string
  - name: orcaMetadataSchema
    type: string
  - name: orcaRuntimeSchema
    type: string
  - name: bronzeCatalog
    type: string
  - name: silverCatalog
    type: string
  - name: goldCatalog
    type: string
  - name: platinumCatalog
    type: string
  - name: enableCdfForRuntime
    type: boolean
    default: true
  - name: enableCdfForMetadata
    type: boolean
    default: false
  - name: storageAccountName
    type: string
    default: ''
  - name: storageConnectorId
    type: string
    default: ''

  


steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python 3.11'
    inputs:
      versionSpec: '3.11'
      addToPath: true


  # Install Terraform manually since TerraformInstaller task is not available
  - script: |
      # Download and install Terraform
      TERRAFORM_VERSION=${TERRAFORM_VERSION:-1.13.1}
      echo "Installing Terraform version: $TERRAFORM_VERSION"
      
      # Download Terraform
      wget -q https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
      
      # Install unzip if not available
      sudo apt-get update && sudo apt-get install -y unzip
      
      # Unzip and install
      unzip -q terraform_${TERRAFORM_VERSION}_linux_amd64.zip
      sudo mv terraform /usr/local/bin/
      
      # Verify installation
      terraform version
    env:
      TERRAFORM_VERSION: $(terraformVersion)

  - task: AzureCLI@2
    displayName: 'Get Login'
    inputs:
      azureSubscription: ${{ parameters.serviceConnection }}
      addSpnToEnvironment: true
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        echo "##vso[task.setvariable variable=servicePrincipalId]$servicePrincipalId"
        echo "##vso[task.setvariable variable=idToken]$idToken"
        echo "##vso[task.setvariable variable=tenantId]$tenantId"

  - task: Bash@3
    displayName: "Login Again"
    inputs:
      targetType: inline
      script: >-
        az login
        --service-principal
        --username='$(servicePrincipalId)'
        --tenant='$(tenantId)'
        --federated-token='$(idToken)'
        --allow-no-subscriptions

  - task: AzureCLI@2
    displayName: 'Terraform Init'
    inputs:
      azureSubscription: ${{ parameters.serviceConnection }}
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        echo "=== Setting up Terraform with Managed Identity Service Connection ==="
        cd $(System.DefaultWorkingDirectory)
        # Ensure subscription context available to TF for OIDC flows
        export ARM_SUBSCRIPTION_ID=$(az account show --query id -o tsv)
        
        terraform init \
          -backend-config="resource_group_name=$(terraform_resource_group)" \
          -backend-config="storage_account_name=$(terraform_storage_account)" \
          -backend-config="container_name=$(terraform_container)" \
          -backend-config="key=orca-ddl/${{ parameters.environment }}/terraform.tfstate" 
    env:
      # Enable Azure OIDC auth for Terraform backend/provider
      ARM_USE_OIDC: true
      ARM_CLIENT_ID: $(servicePrincipalId)
      ARM_TENANT_ID: $(tenantId)
      ARM_OIDC_TOKEN: $(idToken)

  - task: AzureCLI@2
    displayName: 'Terraform Validate'
    inputs:
      azureSubscription: ${{ parameters.serviceConnection }}
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        # Validate Terraform configuration
        # The Databricks provider will use Azure CLI authentication automatically
        echo "Validating Terraform configuration..."
        cd $(System.DefaultWorkingDirectory)
        export ARM_SUBSCRIPTION_ID=$(az account show --query id -o tsv)
        terraform validate
    env:
      ARM_USE_OIDC: true
      ARM_CLIENT_ID: $(servicePrincipalId)
      ARM_TENANT_ID: $(tenantId)
      ARM_OIDC_TOKEN: $(idToken)

  - task: AzureCLI@2
    displayName: 'Terraform Plan'
    inputs:
      azureSubscription: ${{ parameters.serviceConnection }}
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        # Plan Terraform changes
        # The Databricks provider will use Azure CLI authentication automatically
        echo "Planning Terraform changes..."
        cd $(System.DefaultWorkingDirectory)
        export ARM_SUBSCRIPTION_ID=$(az account show --query id -o tsv)
        terraform plan \
          -var="orca_catalog=${{ parameters.orcaCatalog }}" \
          -var="orca_metadata_schema=${{ parameters.orcaMetadataSchema }}" \
          -var="orca_runtime_schema=${{ parameters.orcaRuntimeSchema }}" \
          -var="bronze_catalog=${{ parameters.bronzeCatalog }}" \
          -var="silver_catalog=${{ parameters.silverCatalog }}" \
          -var="gold_catalog=${{ parameters.goldCatalog }}" \
          -var="platinum_catalog=${{ parameters.platinumCatalog }}" \
          -var="environment=${{ parameters.environment }}" \
          -var="enable_cdf_for_runtime=${{ parameters.enableCdfForRuntime }}" \
          -var="enable_cdf_for_metadata=${{ parameters.enableCdfForMetadata }}" \
          -var="storage_account_name=${{ parameters.storageAccountName }}" \
          -var="storage_connector_id=${{ parameters.storageConnectorId }}" \
          -var="ad_group_environment=${{ parameters.adGroupEnvironment }}" \
          -var="databricks_host=${{ parameters.databricksHost }}" \
          -var="databricks_account_id=${{ parameters.databricksAccountId }}" \
          -out=tfplan
    env:
      ARM_USE_OIDC: true
      ARM_CLIENT_ID: $(servicePrincipalId)
      ARM_TENANT_ID: $(tenantId)
      ARM_OIDC_TOKEN: $(idToken)


#  - script: |
#      # Apply Terraform changes
#      terraform apply -auto-approve tfplan
#    displayName: 'Terraform Apply'
#    workingDirectory: $(System.DefaultWorkingDirectory)
#    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

  - script: |
      # Show Terraform outputs
      terraform output -json > terraform-outputs.json
      cat terraform-outputs.json
    displayName: 'Capture Terraform Outputs'
    workingDirectory: $(System.DefaultWorkingDirectory)
    condition: succeeded()

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Terraform Plan'
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)/tfplan'
      ArtifactName: 'terraform-plan-${{ parameters.environment }}'
      publishLocation: 'Container'
    condition: always()

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Terraform Outputs'
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)/terraform-outputs.json'
      ArtifactName: 'terraform-outputs-${{ parameters.environment }}'
      publishLocation: 'Container'
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
